BASE_URL = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER_ENDPOINT = '/api/v1/courier'
LOGIN_COURIER_ENDPOINT = '/api/v1/courier/login'
DELETE_COURIER_ENDPOINT = '/api/v1/courier/'
CREATE_ORDER_ENDPOINT = '/api/v1/orders'
GET_LIST_ORDER_ENDPOINT = '/api/v1/orders'
GET_ORDER_ENDPOINT = '/api/v1/orders/track'
ACCEPT_ORDER_ENDPOINT = '/api/v1/orders/accept/'
